function plot_receiver_stats(a, Tlim, maxRate, maxFrames, maxDelay)
  % Plot SCReAM Receiver Statistics
  % a: Matrix generated by import_receiver_log
  % Tlim: [min max] time e.g [0 100]
  % maxRate: Y-limit for Rate plot (Mbps)
  % maxFrames: Y-limit for Frames plot
  % maxDelay: Y-limit for Delay plot (s)
  % 
  % Example:
  % > a = import_receiver_log('rx_log.txt');
  % > plot_receiver_stats(a, [0 60], 20, 60, 0.5);

  T = a(:,1); 
  % Reset time to start at 0 if needed
  if ~isempty(T)
      T = T - T(1); 
  end
  
  K=3; L=1; % 3 Subplots

  % --- Subplot 1: Receive Rate and Frames Completed ---
  subplot(K,1,L); L=L+1;
  % Plot Rate (Col 2) solid blue, Frames (Col 3) dashed red
  plot(T, a(:,2), 'b', T, a(:,3), 'r--');
  set(gca,'FontSize',12); grid on;
  title('Receive Rate [Mbps] (Blue) & Frames Completed (Red--)', 'FontSize', 10)
  set(gca,'XTickLabel',[]);
  xlim(Tlim);
  if nargin > 2 && ~isempty(maxRate)
      ylim([0 maxRate]); % Limit based on Rate, Frames might clip if scale differs wildly
  end
  legend('Rate', 'Frames', 'Location', 'northwest');

  % --- Subplot 2: Freeze Count and Duration ---
  subplot(K,1,L); L=L+1;
  % Plot Freeze Count (Col 4) and Freeze Duration (Col 5)
  plot(T, a(:,4), 'k', T, a(:,5), 'm:');
  set(gca,'FontSize',12); grid on;
  set(gca,'XTickLabel',[]);
  title('Freeze Count (Black) & Duration [s] (Magenta)', 'FontSize', 10)
  xlim(Tlim);
  % Auto-scale Y usually works best here as freezes are rare/spiky

  % --- Subplot 3: Inter-Frame Delay and Variance ---
  subplot(K,1,L); L=L+1;
  % Plot Total Delay (Col 6)
  % Variance (Col 7) is usually very small (e-05), so we multiply by 1000 for visibility
  plot(T, a(:,6), 'b', T, a(:,7)*1000, 'g');
  set(gca,'FontSize',12); grid on;
  title('Total IF Delay [s] (Blue) & Variance [ms^2] (Green)', 'FontSize', 10)
  if nargin > 4 && ~isempty(maxDelay)
      ylim([0 maxDelay]);
  end
  xlim(Tlim);

  xlabel('Time [s]');
end